### ISSUE TITLE
Vendor dependencies

### ISSUE THREAD

**Issue by mcandre** [pierrec/lz4#10]
Please vendor lz4's dependencies, so that users don't have to manually resolve missing deps.

Example:

```console
$ cd $GOROOT/src/github.com/pierrec/lz4
$ git submodule update --init --recursive
$ git submodule add git@github.com:pierrec/xxHash.git vendor/github.com/pierrec/xxHash
$ git add .gitmodules vendor
$ git commit -m 'vendor github.com/pierrec/xxHash'
$ git push
```

**Comment by pierrec** [comment]
Sorry, I will not vendor dependencies.
If you install the package via `go get` it will install them for you.
Otherwise, use a tool like glide (https://glide.sh) to manage the dependencies.
