### ISSUE TITLE
Block dependency support?

### ISSUE THREAD

**Issue by viric** [pierrec/lz4#101]
I was trying to work with some lz4 and I found they are built with block dependency. The current code doesn't support them so I end up calling "lz4cat".

This is just a vote to get the decoding support for it.

**Comment by pierrec** [comment]
@viric do you have any example file you could share?

**Comment by viric** [comment]
Files are created by this frame compressor:
https://python-lz4.readthedocs.io/en/stable/lz4.frame.html

I think that you can create an equivalent with the cmdline lz4 like "lz4 -BD -B1000"     (blocks of 1000 bytes)
