### ISSUE TITLE
lz4.Reader in v4.1.1 gives EOF error incorrectly

### ISSUE THREAD

**Issue by work-chausat** [pierrec/lz4#106]
lz4.Reader in v4.1.1 gives EOF error, but in actuality the data haven't read completely.  In my test scenario and compressed data, i got 11 records with no error by v4.0.2, but if i use the same test data and switched to v4.1.1(ConcurrencyOption is set to 3), i read only 1 record and many EOF errors. But if i set ConcurrencyOption to 1, i got the correct 11 records.

**Comment by pierrec** [comment]
Any chance to get a reproducing input file?

**Comment by tutububug** [comment]
The concurrent reader(called A) will save a error in member of frame blocks error when reading from one source reader(called B), the error will be EOF when reader B is read completely, at this time, if reusing reader A to reader the other source reader(called C), reader A will return the EOF error directly without reading any data.

**Comment by pierrec** [comment]
Fixed with PR #111, included in new version v4.1.2.
