### ISSUE TITLE
Concurrency decompress performance is not promoting any more when read option(concurrency number) rise. 

### ISSUE THREAD

**Issue by tutububug** [pierrec/lz4#107]
When set the concurrency number from 1 to 2, it shows much more throughput. But set the concurrency number to 3 or more, it no more rise.
I found the frame blocks doing uncompress(consuming) is not slower than do reading(producing), 
In file “lz4stream/block.go”, FramDataBlock method Compress has such a code: 
`data = data[:len(src)] // trigger the incompressible flag in CompressBlock.
`
So this means the original data write down without compressing. Why?

**Comment by pierrec** [comment]
Sorry, I missed your issue.
The LZ4 stream format supports uncompressed blocks. This means saving a few bytes when the data is indeed uncompressible, instead of using the compressed but longer than source blocks.
Does this answer your question?

**Comment by tutububug** [comment]
Get it, thanks.
