### ISSUE TITLE
Alternating byte values don't compress

### ISSUE THREAD

**Issue by pixel27** [pierrec/lz4#11]
I was trying to run some benchmarks on the code by compressing some text files in the  500k - 2mb range, and they just weren't compressing.  So I wrote this for a test:

`

    package main

    import (
        "fmt"
        "github.com/pierrec/lz4"
    )

    func main() {
        input := make([]byte, 64 * 1024)

        for i := 0; i < 64*1024; i += 1 {
            input[i] = byte(i & 0x1)
        }
        output := make([]byte, 64 * 1024)

        c, e := lz4.CompressBlock(input, output, 0)

        if c == 0 && e == nil {
            fmt.Printf("Won't compress.\n")
        } else if e != nil {
            fmt.Printf("Error: %s\n", e)
        } else {
            fmt.Printf("Compressed to %d bytes.\n", c)
        }
    }
`

This should produce a 64k buffer of alternating 1s and 0s. LZ4 reports that the block won't compress, which feels wrong to me.  If I change the buffer to only contains 0s, then it compresses to 50833 bytes, which seems a bit large.

Changing the code to use CompressBlockHC does appear to work.  So i'm guessing there is a issue with the normal compressing code?

**Comment by pierrec** [comment]
Yes this is a bug introduced lately. I will revert the offending commits.

**Comment by pierrec** [comment]
This is now fixed.
