### ISSUE TITLE
Broken data integrity on compression

### ISSUE THREAD

**Issue by xlab** [pierrec/lz4#12]
Hello, this commit https://github.com/pierrec/lz4/commit/d9ddf251e623fd7f22c86b76c5932c1a3784a183 introduces data corruption upon compression, I was just able to trace it in 20hours of fiddling around. Since we had data integrity checks in the unmarshalling logic, I had to check unmarshalling first..

**3 things that I dislike about this commit:**

1) Using of `unsafe` package bans it from Google App Engine, also removes any guarantees from runtime whatsoever. This is not what I'd expect from a simple compression library.

2) Relying on the endianness of the host machine is evil (plus, Rob's opinion: https://commandcenter.blogspot.ru/2012/04/byte-order-fallacy.html), I won't believe this is really necessary there to gain a speed up.

3) These changes breaks data integrity (no surprise).

I don't have a reproducible result to share, but maybe the tests should be improved to cover the code better. And the host endianness if you'd prefer to stick with it.

Find the details of my environment below
```
$ go version
go version go1.8 darwin/amd64

$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/xlab/Documents/dev/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/dr/2vrbtj0j7kl1yy32kp5cpn040000gn/T/go-build154721013=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

Anyway, nice package! I'm fine on the latest working commit 7f1eefc66a72ee8dbf4bc789bb525a49ecd7395f

**Comment by pierrec** [comment]
I am sorry to hear that it broke your program.
I am also not keen on using unsafe and have been wondering whether or not to keep it.
Since it actually breaks data integrity (also see issue #11), I will undo the offending commits.

**Comment by pierrec** [comment]
This is now fixed, with test added.
