### ISSUE TITLE
go.mod

### ISSUE THREAD

**Issue by 89z** [pierrec/lz4#124]
It looks like the `go.mod` was removed a while back: https://github.com/pierrec/lz4/commit/377214e3044ff9f12d996f3037fb8c3e3ad16b49

However this is not ideal, as it causes anyone who uses this package to get
indirect entries in their own `go.mod`:

~~~go
github.com/frankban/quicktest v1.11.3 // indirect
~~~

**Comment by pierrec** [comment]
Please use the current v4 branch version. Thanks.
