### ISSUE TITLE
Make `lz4stream` public accessible ?

### ISSUE THREAD

**Issue by 10000TB** [pierrec/lz4#145]

**Comment by pierrec** [comment]
Could you tell me what your use case is? The lz4stream pkg is not intended for public use.

**Comment by 10000TB** [comment]
Hi !

An example use case is use 'Frame''s ParsehHeader to check if the data is lz4 archive.

Practically, we have a scenario where we take an 'io.Reader', it can be regular file, or a lz4 archive, but we are not told which one it is. We need to tell by reading header and find out. I find that frame implements a ParseHeader which returns nil or error to indicate if a valid lz4 frame header can be retrieved from first 32 bytes, which is exactly what is needed.

Alternative is I copy over your ParseHeader logic implemented by Frame struct, that'd work, but creates duplicate code, especially the magic number, legacy one, and the upper 16bits one...

**Comment by 10000TB** [comment]
I am happy to send a PR, but want to see if that is sth you ok with that, and what you suggest changing

**Comment by pierrec** [comment]
OK, this is a good use case, thanks for sharing.
I am happy for you to send a PR, but I'd rather leave the lz4stream package unexposed as it does a lot more than just header parsing.
I propose that you expose the method that you are interested in the Reader so that the code isnt duplicated but still get you where you need to be. WDYT?

**Comment by 10000TB** [comment]
That is better ! - reusing same frame struct from a reader, and looks like a smaller change in comparison

**Comment by 10000TB** [comment]
sent https://github.com/pierrec/lz4/pull/147 -- but I chose to make it a separate function than attached to Reader, just not to interfere with existing elegance of Reader inits etc
