### ISSUE TITLE
go get github.com/pierrec/lz4  failed

### ISSUE THREAD

**Issue by PhilipTang** [pierrec/lz4#15]
# github.com/pierrec/lz4
src/github.com/pierrec/lz4/block.go:120: undefined: mfLimit
src/github.com/pierrec/lz4/block.go:128: undefined: hashLog
src/github.com/pierrec/lz4/block.go:128: invalid array bound 1 << hashLog
src/github.com/pierrec/lz4/block.go:129: undefined: minMatch
src/github.com/pierrec/lz4/block.go:129: undefined: hashLog
src/github.com/pierrec/lz4/block.go:134: undefined: hasher
src/github.com/pierrec/lz4/block.go:140: undefined: skipStrength
src/github.com/pierrec/lz4/block.go:141: undefined: minMatch
src/github.com/pierrec/lz4/block.go:143: undefined: hasher
src/github.com/pierrec/lz4/block.go:159: undefined: skipStrength
src/github.com/pierrec/lz4/block.go:159: too many errors

**Comment by pierrec** [comment]
Hello,

Not sure about your go setup?
It works fine for me:
$ go get -v github.com/pierrec/lz4
github.com/pierrec/lz4 (download)
github.com/pierrec/xxHash (download)
github.com/pierrec/xxHash/xxHash32
github.com/pierrec/lz4
$ go version
go version go1.8.1 darwin/amd64
$ echo $GOPATH
XXX/sandbox/tmp

**Comment by EdoardoPedrotti** [comment]
Same problem,
..\..\pierrec\lz4\block.go:120: undefined: mfLimit
..\..\pierrec\lz4\block.go:128: undefined: hashLog
..\..\pierrec\lz4\block.go:128: invalid array bound 1 << hashLog
..\..\pierrec\lz4\block.go:129: undefined: minMatch
..\..\pierrec\lz4\block.go:129: undefined: hashLog
..\..\pierrec\lz4\block.go:134: undefined: hasher
..\..\pierrec\lz4\block.go:140: undefined: skipStrength
..\..\pierrec\lz4\block.go:141: undefined: minMatch
..\..\pierrec\lz4\block.go:143: undefined: hasher
..\..\pierrec\lz4\block.go:159: undefined: skipStrength
..\..\pierrec\lz4\block.go:159: too many errors

**go version** go1.8.1 windows/amd64

I am trying to compile influx telegraf.

**Comment by pierrec** [comment]
I have successfully compiled telegraf using the instructions provided there.
Maybe try to compile it from an empty GOPATH and see where it goes?
