### ISSUE TITLE
i got an error:bad magic number

### ISSUE THREAD

**Issue by www13059690** [pierrec/lz4#152]
when i want to decompress a binary file , i got this error "lz4: bad magic number"
 
`
func main(){
	fi,err := os.Open("1compress")
	if err != nil{
		print("wrong")
	}
	fw,_ := os.OpenFile("deCompress",os.O_WRONLY|os.O_CREATE|os.O_TRUNC,0777)
	err = decompress(fi,fw)
	if err != nil{
		print("wrong" + err.Error())
	}
}
func decompress(r io.Reader, w io.Writer) error {
	zr := lz4.NewReader(r)
	_, err := io.Copy(w, zr)
	return err
}`

**Comment by www13059690** [comment]
im sorry , i dont know how to insert code correctly.
maybe u can view code by this url
https://paste.ubuntu.com/p/dF5cnWht6C/

**Comment by pierrec** [comment]
The error means that this is not an LZ4 compressed file.

**Comment by pierrec** [comment]
Closing as it seems like a user error. Feel free to reopen with additional information if needed.
