### ISSUE TITLE
Discrepancy between decoders for match that is partially in the dictionary

### ISSUE THREAD

**Issue by greatroar** [pierrec/lz4#160]
With an appropriately sized dst,

```go
// match length = 8+minMatch, offset = 4
decodeBlock(dst, []byte("\x08\x04\x00"), []byte("---1234"))
```

produces "123412341234" when using the assembler decoders. But the portable decoder returns -2.

**Comment by greatroar** [comment]
The [block format spec](/lz4/lz4/blob/dev/doc/lz4_Block_format.md) says the last five bytes of input must be literal bytes. So the portable decoder is correct in rejecting the input. It's still unfortunate that the behavior differs, though.

**Comment by pierrec** [comment]
So if I understand this right, you are saying that the asm decoder(s) behave differently than the Go one on invalid input?
If so, I think that the asm decoder shuold be fixed, don't you agree?

**Comment by greatroar** [comment]
Either that, or the portable decoder should handle this input too. I don't know if it occurs in the wild.
