### ISSUE TITLE
compression and decompression MB/s

### ISSUE THREAD

**Issue by jojo05** [pierrec/lz4#17]
Did you run any tests to compare the overhead of the Go version vs the results for the optimized C version [1] ?

[1] https://github.com/lz4/lz4

Thanks

**Comment by pierrec** [comment]
I havent done any formal tests, just tried the cli tools (Go and C) on large files (>100MB) and on average the Go version is about 50% slower (go1.8.1).

**Comment by jojo05** [comment]
Wow! That's a big difference. Thank you
