### ISSUE TITLE
quick question about v2 to v4 API compatibility

### ISSUE THREAD

**Issue by sten0** [pierrec/lz4#176]
Hi!

I'm wondering whether or not v4 is API compatible with v2.

Thanks in advance,
Nicholas

**Comment by pierrec** [comment]
Hello,

The API is not compatible but the file format is. Does that help?

**Comment by sten0** [comment]
Yes, that does, thank you :-)  I'm investigating prerequisite steps to updating Debian's Syncthing package, and given that the API between v2 and v4 is not compatible it seems we'll need a new golang-github-pierrec-lz4.v4 package to provide github.com/pierrec/lz4/v4.  I wanted to be 100% certain before going down that path, because v4 depends on another two new packages, and that delays progress quite a bit.

Thank you for taking the time to reply so quickly,
Nicholas
