### ISSUE TITLE
Please cut a new v3 maintenance release!

### ISSUE THREAD

**Issue by lizthegrey** [pierrec/lz4#182]
hi! honeycomb is currently using lz4 from a git sha after the latest round of backports, but bump of the deps in go.mod plus official release tag might be a good idea. thanks!

I know, I know, we need to move onto v4, but the `Seek()` API going away has made the transition non-trivial for us, and for some reason consuming to `io.Discard` doesn't have quite the same behaviour.

**Comment by pierrec** [comment]
Hello! done, thanks for reminding me.
I would be curious to see what the issue is wrt io.Discard. Could you open an issue about it with a reproducer (if possible)?

**Comment by lizthegrey** [comment]
closed by https://github.com/pierrec/lz4/releases/tag/v3.3.5

thanks, and will open the issue.

**Comment by lizthegrey** [comment]
Figured out the problem, and sadly it's an _encode-side_ problem on our side cause by buffer mismanagement.
