### ISSUE TITLE
go get: file too large

### ISSUE THREAD

**Issue by filinvadim** [pierrec/lz4#185]
My project uses Segmentio kafka-go which is dependent on this project. While i'm calling `go mod tidy` i'm constantly getting below error:
```
... imports
	github.com/segmentio/kafka-go imports
	github.com/segmentio/kafka-go/compress imports
	github.com/segmentio/kafka-go/compress/lz4 imports
	github.com/pierrec/lz4/v4: github.com/pierrec/lz4/v4@v4.1.14: write ***/go/pkg/mod/cache/download/github.com/pierrec/lz4/v4/@v/v4.1.14.zip2445184339.tmp: file too large
```
Do we really need this tmp file?

**Comment by pierrec** [comment]
Hmm. I dont get this error message. Could you retry by clearing out your cache first?

**Comment by filinvadim** [comment]
Same result with `go clean -modcache`

MacOS Monterey 12.4

**Comment by filinvadim** [comment]
Found the issue:
https://github.com/Homebrew/brew/issues/10275

That's why Linux is better than MacOS.
