### ISSUE TITLE
lz4 reader read block until buf is full?

### ISSUE THREAD

**Issue by pieropio** [pierrec/lz4#190]
for a io.reader
        n, err := lz4Reader.read(buf)
i expect read should directly get any of current result and return the current read length, but it block until buf is full.
it cause problem:
https://go.dev/play/p/uFyyFbCL7Yp

**Comment by pierrec** [comment]
I am not sure what you are experiencing as the example you gave works fine?

**Comment by pieropio** [comment]
sorry, i gave a wrong version code. see https://go.dev/play/p/vy3P3HZepF_r, which use v4 version.
in code, i write data with length 11 to writer, then I use a buffer with length 12 to read back. But the v4 version can't read the result, it try to fullfill the 12 length buffer.

**Comment by pierrec** [comment]
Because you need to handle the error, which in this case is io.EOF as expected.

See https://go.dev/play/p/tikjFzpdika

**Comment by pieropio** [comment]
What if (in line 20) the writer was not close the the pipe? (it is used to write other message later, in my application). In which case, the writer have flush the message, but reader is still stucked.
ps: v3 is works fine, and snappy https://github.com/golang/snappy works fines.

**Comment by t0350** [comment]
@pierrec sorry for bother you.
It seems like that the read ends when `len(read_buf) == 0`, and this may leads to read block. Is this as your expectation or something we misunderstood?
As this example, https://go.dev/play/p/xu9MkdTk0Oy, `zw.close` is removed now, read will block and exit with `all goroutines are asleep`.
