### ISSUE TITLE
[RSVP] What is the source of xxh32zero.go?

### ISSUE THREAD

**Issue by sten0** [pierrec/lz4#194]
Hi @pierrec,

What is the source of xxh32zero.go?  I'm guessing your ported the reference implementation, and that the unreachable url in xxh32zero.go is a form of attribution.  Or is this someone else's work that you then built off of?

I was able to circumvent the other issues by excluding files mentioned in #178 and disabling associated tests.  Debian ftpmasters are treating #194, this issue, as a hard blocker.  Finally this issue is also blocking work on reverse dependencies, so please reply asap :)

Thank you,
Nicholas

**Comment by pierrec** [comment]
Hi @sten0, sorry for not addressing the other issues, I maintain this lib on my freetime, and it has been very scarce!
I have updated the header of that file so it is now clearer on how this got built (you guessed right).
Let me know if this is OK.

**Comment by sten0** [comment]
It's OK, and as someone who also does freetime work, I know what you mean.
Sorry for having to bother you with paperwork-type issues that take up free
time.  Aha, so it was a "shortest effective header" experiment! ;)  I can
confirm that before you committed the fix for this issue, it confused one
person (not me), who is familiar with copyright review.

*WOW* I didn't expect that fast of a reply and fix, thanks, and I imagine
Cyan4973 appreciates it too.
