### ISSUE TITLE
lz4: invalid source or destination buffer too short

### ISSUE THREAD

**Issue by xguo-prestolabs** [pierrec/lz4#195]
I have a compressed lz4 file (which is produced by a cpp program using c lz4 lib). I can decode it normally using lz4 command tool, 
but using golang lz4 cmd tool, it failed with this error message:
      lz4: invalid source or destination buffer too short

what can be the possible cause of this issue?

**Comment by xguo-prestolabs** [comment]
I cannot upload the sample file, I got the error message says that file type not supported.

**Comment by pierrec** [comment]
@xguo-prestolabs thanks for the report. I would be keen on getting the file uncompressed version though as the bug may be a variety of places. I would understand if you cannot share it.

**Comment by pierrec** [comment]
Closing, plz reopen if needed.
