### ISSUE TITLE
Very slow performance when sending on a socket.

### ISSUE THREAD

**Issue by alexfernandez** [pierrec/lz4#20]
I am writing an application that sends compressed messages through a socket. When using LZ4 performance is very low: about 7k messages/second for sending a trivial string. If I change `BlockDependency` from `true` to `false` then it raises to about 60k messages/second, still very far from the ~500k messages/second I get without compression.

It is very weird because using your [Node.js package](https://github.com/pierrec/node-lz4) for a pure-JavaScript sender and writer, I am getting more than 300k messages/second with compression enabled. Can you tell what is going on? What am I doing wrong?

Full test code (sender and receiver) is attached. Usage: in two terminals:

```
$ go run receiver-test.go
$ go run sender-test.go
```

Thanks!

[lz4-test.zip](https://github.com/pierrec/lz4/files/1410453/lz4-test.zip)

**Comment by pierrec** [comment]
Hello,

Block dependency will definitely introduce bottlenecks, however the Go implementation should not be slower than the js one.
It's been a long time since I wanted to revisit this (it is my first go project and used this implementation as a learning exercise) and I may do so on my free time (so dont expect any quick fix unfortunately).

Thanks for the test case, it will help in figuring out what is going on.

**Comment by alexfernandez** [comment]
Thanks for looking into it! Adding a `bufio.Writer` so that the output is buffered before being sent is not helping either.

I am also having issues in interoperability between Node.js and Go when Go sends, but I am not sure about why.

**Comment by pierrec** [comment]
I have revisited the implementation and it is much faster now (getting the throughput from 24k events/s to 10millions/s).
I have dropped support for BlockDependency though as it adds complexity for no real benefit (at least in the tests that I have carried out).

I am unsure about the NodeJS / Go issues you are running into though. Some sample code would help ;).

**Comment by alexfernandez** [comment]
BlockDependency is good to have for compatibility purposes when you don't control who is sending and how.

Thanks for the good work!
