### ISSUE TITLE
I got error 403

### ISSUE THREAD

**Issue by navidof5** [pierrec/lz4#201]
hello 
I'm trying to install some tools from @ProjectDiscovery and in some cases like Subfinder and Proxify when I run the command that suggests installing those tools I get 403 forbidden from your repo. Here are the images that show the error I get:
![4033333](https://user-images.githubusercontent.com/89974434/201470679-f9c73b0f-a591-4e56-bc40-c8d9c0202fad.png)
![2022-11-07_00h08_34](https://user-images.githubusercontent.com/89974434/201470698-0809a8e4-3166-4918-b0f5-80370dd4224f.png)
Do you have any idea why this happened to my VPS??? Please help me if you can. It would be greatly appreciated if you could help me.

**Comment by pierrec** [comment]
Hi @navidof5,
I am sorry but this has nothing to do with this package but golang.org's proxy.
