### ISSUE TITLE
.unity3d lz4 compression and decompression

### ISSUE THREAD

**Issue by SouleaterLC** [pierrec/lz4#206]
hi im new at this and i want to know if i can uncompress and compress the data again of a unity3d file when i try it says 
0s]lz4: bad magic number
and i tested with another repository and worked the decompression part this one: https://github.com/subdiox/UnityLz4

but my problem is if i can compress it again here 

thank you.

**Comment by pierrec** [comment]
This package supports the [LZ4 frame format](https://github.com/lz4/lz4/blob/dev/doc/lz4_Frame_format.md), which should work if unity does too. I am sorry I have no knowledge about Unity.
