### ISSUE TITLE
Reader oriented encoder

### ISSUE THREAD

**Issue by oakad** [pierrec/lz4#210]
Right now, `Writer` is used for compression and `Reader` is used for decompression. However, some storage APIs, namely AWS S3 and kind, insist on having a `Reader` as a body of file to upload.

S3 style APIs are incredibly popular and will stay with us for the indefinite future.

We, of course, can work around this limitation by means of a helper goroutine and an `io.Pipe`, but this adds quite a bit of overhead when many objects are to be uploaded in compressed form.

From the look of it, it should not be too difficult to make an `EncodingReader` object, which takes a plain data `Reader` as a parameter and exposes a `Reader` for compressed data (that is, performs a logical opposite of the presently available `lz4.Reader` object).

I think, such a feature will be most useful for people using cloud storage.

**Comment by pierrec** [comment]
Hello, it makes sense to have it. I currently dont have time to work on this but am open to PRs :).

**Comment by oakad** [comment]
Kind of weird how http.Request requires reader for the body, yet Go supplied compressors, like gzip, have not support for handling it. Nobody cares about uploads? :-)

**Comment by oakad** [comment]
Added a pull request (#211) . Seems to work.

**Comment by nanokatze** [comment]
Is there any reason you don't want to use https://pkg.go.dev/io#Pipe for this?

**Comment by pierrec** [comment]
Closed as PR is merged.
