### ISSUE TITLE
Help decoding a lz4 block format

### ISSUE THREAD

**Issue by ut0mt8** [pierrec/lz4#217]
This is not really a bug but I'm really struggling decoding what I'm pretty sure is a LZ4 block.

The uncompressed file is :

````
00000000  25 00 00 00 e2 00 06 57  58 43 56 42 4e 7f ff ff  |%......WXCVBN...|
00000010  ff 80 00 01 00 f0 02 24  0e 14 00 08 0a 50 4f 49  |.......$.....POI|
00000020  55 59 54 52 45 5a 41 01  ab a5 d4 cf              |UYTREZA.....|
````

you can notice the first 4 byte that should be a length (little Endian). 

My test program : 
````
    f, err := os.Open("data.data")
    
    var compressed_length int32
    binary.Read(f, binary.LittleEndian, &compressed_length)
    fmt.Printf("compressed_length: %d\n", compressed_length) // 37 seems the uncompress length more or less

    compressed := make([]byte, 36) // size of the file - 4 bytes length - 4 crc
    binary.Read(f binary.BigEndian, &compressed)

    decompressed := make([]byte, 1000000) // enough size for decompressed buffer
    l, err := lz4.UncompressBlock(compressed, decompressed)
    if err != nil {
        panic(err)
    }

    fmt.Printf("uncompressed_length: %d\n", l)
````

My question is : is there a way to decode lz4 without knowing the size of the compressed data (cause In my case it's not trivial at all to get it).

**Comment by pierrec** [comment]
I dont think there is a way. At best you could try to stop when you encounter your first parse error.

**Comment by ut0mt8** [comment]
Maybe I can count for the number of decoded bytes?

**Comment by pierrec** [comment]
> Maybe I can count for the number of decoded bytes?

If you know the size of the uncompressed data then yes you could do that.

**Comment by ut0mt8** [comment]
Ok I find a way to reliably decompress my stuff (sstable from cassandra, super weird format). Thks.
