### ISSUE TITLE
Skippable frames support

### ISSUE THREAD

**Issue by virvum** [pierrec/lz4#224]
Is there any way to read and write [skippable frames](https://github.com/lz4/lz4/blob/dev/doc/lz4_Frame_format.md#skippable-frames)? I would like to write some metadata to the lz4 header and also extract this metadata from the header.

**Comment by pierrec** [comment]
Skippable frames are [supported](https://github.com/pierrec/lz4/blob/v4/internal/lz4stream/frame.go#L94).
Let me know if something if off.
