### ISSUE TITLE
v2.0 dropped support of Go-1.9.x

### ISSUE THREAD

**Issue by sbinet** [pierrec/lz4#24]
commit https://github.com/pierrec/lz4/commit/7f4bd64aba4b03e434003ac9e586d71d444527f8 is using the new `strings.Builder` API for `Header.String()`.

could this be `build-tag` guarded so one can still build `lz4` with Go-1.9.x?

**Comment by abhiutd** [comment]
Yeah, it would be great to have it backward-compatible...

**Comment by sbinet** [comment]
wow, that was fast :)

**Comment by pierrec** [comment]
thanks for the pull request!
