### ISSUE TITLE
jsonlz4 / mozlz4?

### ISSUE THREAD

**Issue by frioux** [pierrec/lz4#28]
Mozilla has a weird lz4 format that is simply an lz4 compressed json file with a header, as far as I can tell.  I haven't been able to find any documentation on the format but I did find this project, which works: https://github.com/badboy/jsonlz4cat.  In the project there is a file that defines the format as:

``` 8 bytes   | 4 bytes     | [remaining]
[mozLz40\0] {u32 outsize} {compressed data}```

I figured I could implement a reader in Go with something like the following:

```golang
package main

import (
	"fmt"
	"io"
	"os"

	"github.com/pierrec/lz4"
)

const magic_header = "mozLz40\x00"

func main() {
	if len(os.Args) != 2 {
		panic("must pass one arg")
	}
	file, err := os.Open(os.Args[1])
	if err != nil {
		panic(err)
	}

	header := make([]byte, len(magic_header))
	_, err = file.Read(header)
	if err != nil {
		panic(err)
	}
	if string(header) != magic_header {
		panic("wrong header")
	}

	size := make([]byte, 4)
	file.Read(size)
	x := lz4.NewReader(file)
	_, err = io.Copy(os.Stderr, x)
	if err != nil {
		panic(err)
	}
}
```

Unfortunately I consistently get `lz4: bad magic number`.  I suspect that `lz4` is looking for it's own header and that because this is some other file format it's not there.  Do you know of a way I can make this work?

**Comment by pierrec** [comment]
Hello,

Indeed your analysis is correct: the lz4 reader and writer support the lz4 frame format, which has its own header.
To make your case work, you need to use the lower level functions Compress() and Uncompress() that only expect raw bytes or the compressed data.

Let me know how this goes.

**Comment by frioux** [comment]
Thanks for the tip, totally worked; here's what I did:
```golang
	size := make([]byte, 4)
	file.Read(size)

	src, err := ioutil.ReadAll(file)
	if err != nil {
		panic(err)
	}

	out := make([]byte, len(src)*10) // XXX should make this use size
	_, err = lz4.UncompressBlock(src, out)
	if err != nil {
		panic(err)
	}
	fmt.Print(string(out))
```

**Comment by crazy-max** [comment]
@frioux Any hint/snippet to compress data back ? I've found [this](https://dxr.mozilla.org/mozilla-central/source/toolkit/mozapps/extensions/AddonManagerStartup.cpp#170) and [this](https://github.com/avih/dejsonlz4/blob/master/src/ref_compress/jsonlz4.c) if it can help. Thanks!

**Comment by frioux** [comment]
Like this https://github.com/frioux/leatherman/blob/master/pkg/mozlz4/mozlz4_test.go#L127
