### ISSUE TITLE
LZ4 C library incompatible?

### ISSUE THREAD

**Issue by binary132** [pierrec/lz4#31]
Hello, I am still working on debugging my (very simple) C++ program, but it uses the LZ4 library to decompress the output of this Go package.

I noticed that `lz4cat` and `lz4c` are both able to decompress this output, but the C library approach is not working.  I was wondering if you know of some incompatibility there?

For what it's worth, I am using the latest C library at revision c4dbc37b3ce085a05441124fee4a8144dc149b05 (https://github.com/lz4/lz4/commit/c4dbc37b3ce085a05441124fee4a8144dc149b05).

Cheers!

**Comment by binary132** [comment]
Another way of phrasing this question might be: what version of the C library is the output of this package compatible with?

**Comment by pierrec** [comment]
Hello,
Well the Go package supports the LZ4 stream format, as your tests show using the cli lz4 standard tools.
AFAIK that's all that is required.
If your program cannot decode this output, try compressing it using the cli tools and use that first with your program. Unless this fails, provide that output so that I can look at it to help.

**Comment by binary132** [comment]
I think the issue is I wasn't using the stream API.  I'll have a closer look at the Go implementation and report back if there's still an issue.

**Comment by binary132** [comment]
Hi, just to confirm, I was able to get it to work by using the interface in `lz4_frame.h`.  The basic LZ4 interface in `lz4.h` does not support the streaming frame protocol.

**Comment by pierrec** [comment]
Done, thank you.

**Comment by zkkxu** [comment]
> Hi, just to confirm, I was able to get it to work by using the interface in `lz4_frame.h`. The basic LZ4 interface in `lz4.h` does not support the streaming frame protocol.
> 
> Hopefully this information will be useful to someone! You should mention in the README which version of the LZ4 C library you're compatible with, btw!

Does that mean I can't use any interface defined in `lz4.h` unless `lz4frame.h` when I write a c server use c API  connecting a go client?
