### ISSUE TITLE
module name in go.mod for v2

### ISSUE THREAD

**Issue by albertjin** [pierrec/lz4#39]
It should have v2 in `go.mod`
```
module github.com/pierrec/lz4/v2
```

and then this example works,
```Golang
import "github.com/pierrec/lz4/v2"

func test() {
    // ...
    text := lz4.NewReader(compressed)
    // ...
}
```

**Comment by albertjin** [comment]
This leads to more changes and seems incompatible if imported by projects without module enabled. The root cause is because the revision number is not considered with semantic versioning in mind. 😂

**Comment by pierrec** [comment]
If you want the latest updates, v2.1.0 does incorporate them.
Doing the following should work:

    require github.com/pierrec/lz4 v2.1.0

The go.mod file was setup this way so as not to upset packages that are not modules aware yet.
See issue #33.

**Comment by jefferai** [comment]
I realize this was closed but I came here intending to file an issue with the same request and then found this.

Can I request that, although you're looking at backwards compat now, in the Go 1.14 timeframe (at which point only 1.12-1.14 will be supported, and thus all supported versions support modules) you make this change?

**Comment by pierrec** [comment]
Hello,

I am definitely in favor of doing this change and following the modules naming convention. However, this has to not clash with the usage of this package by users, so would need to consider it when getting to the 1.14 timeframe.

Keeping this issue open as a reminder.

**Comment by bcmills** [comment]
As noted in https://github.com/pierrec/lz4/issues/33#issuecomment-432377866, the current approach — a `v2` major version without a `/v2` suffix on the module path — is not supported.

The fact that it appears to work at all today is due to a bug (golang/go#32695), which I am planning to fix for Go 1.13.

**Comment by pierrec** [comment]
Thanks for the heads up. I agree that it is currently wrong and should be fixed. Need to think about the best way to not upset the packages importing this package though.

**Comment by bcmills** [comment]
For a short-term fix, you could simply remove the `go.mod` file in the next patch release. (That would at least buy you some time to plan out a more in-depth solution.)

For the longer term, see http://golang.org/wiki/Modules#releasing-modules-v2-or-higher for some more in-depth discussion.

**Comment by pierrec** [comment]
Removed support for modules in version 2.
New branch for version 3 (v3) supports go modules.
