### ISSUE TITLE
Can the lz4.Reader uncompresses data compressed by lz4.CompressBlock?

### ISSUE THREAD

**Issue by sreekanth-cb** [pierrec/lz4#45]
```
dst = make([]byte, len(src))
	ht := make([]int, 64<<10)
	n, err := lz4.CompressBlock(src, dst, ht)
	if err != nil {
		fmt.Println(err)
	}
	if n >= len(src) {
		fmt.Printf("`%s` is not compressible", src)
	}
	dst = dst[:n]
	
        br := bytes.NewBuffer(dst)
	zr := lz4.NewReader(br)
	var out bytes.Buffer
	_, err = io.Copy(&out, zr)
	if err != nil {
		log.Fatal(err) .  // bad magic number error is thrown here. Looks like this isn't possible?
	}
```

**Comment by pierrec** [comment]
Hello,

No it cannot. The lz4.Reader can only read data coming from an LZA [stream](http://fastcompression.blogspot.com/2013/04/lz4-streaming-format-final.html) for instance one generated by an lz4.Writer.

lz4.UncompressBlock can read data from lz4.CompressBlock or lz4.CompressBlockHC though.

**Comment by sreekanth-cb** [comment]
Thanks @pierrec for the quick response! UncompressBlock looks like has the restriction of having a pre allocated big enough output/result buffer requirement? Is there a way to work it around ?

Some random links from googling shown that computing the theoretical limit of an uncompressed buffer from the compressed lz4 buffer size is pretty huge.

**Comment by pierrec** [comment]
Unfortunately, there isnt. You could use lz4.CompressBlockBound, which is what you are talking about.
People tend to prepend their compress buffer with the size of the uncompressed data and use it to size the buffer.

**Comment by sreekanth-cb** [comment]
Yes..As that involves a disk format change, didn't try that for the current project. 
Thanks for the quick responses.
