### ISSUE TITLE
Decompression destination buffer out of bound on ARM systems.

### ISSUE THREAD

**Issue by mingma79** [pierrec/lz4#51]

**Comment by mingma79** [comment]
We run into an issue, on an ARM system, we basically compressed a 8KB data into a buffer, then decompress it into another 8KB buffer. Depending on the data pattern, sometimes we hit a decompress error, complaining about the decompress destination buffer is too small.

"lz4: invalid source or destination buffer too short"

Note that it only happen on ARM system. On x86, it runs fine.

I looked at decodeBlock() in decode_other.go, line 23,
It looks like we are checking if the destination buffer has at least 18 bytes left, but we could end up copy more than 18 bytes into the destination buffer.

**Comment by pierrec** [comment]
Can you reproduce it on x86 by building it with the noasm build tag?
e.g. go build -tags noasm

Also, can you send the sample data for which it fails?

**Comment by mingma79** [comment]
[origdata.tar.gz](https://github.com/pierrec/lz4/files/3532257/origdata.tar.gz)
Yes, I can reproduce it with "-tags noasm" option on x86.
Attached please find the data sample. thanks

**Comment by mingma79** [comment]
Our GO version is 1.12.7
lz4 version: github.com/pierrec/lz4 v2.2.6+incompatible h1:6aCX4/YZ9v8q69hTyiR7dNLnTA3fgtKHVVW5BCd5Znw=


the size of original buffer is 8192 bytes, the size of compressed buffer is 4822 bytes. Then if we decompress it into another 8k buffer, it will fail. But if we decompress it into a 8192+2 bytes buffer, it will succeed.

**Comment by pierrec** [comment]
Thank you for your report and the corresponding reproducer.
Fixed in latest master and in v3.0.2.
Please test and close this issue or let me know otherwise.
