### ISSUE TITLE
Go module support

### ISSUE THREAD

**Issue by GuillaumeLescure** [pierrec/lz4#56]
Hi,

I'm not sure the new Go Module system is integrated in this project.
Maybe I'm using this module badly but, in my project, when I add :

go.mod
`require github.com/pierrec/lz4 v3.1.0`

I get :
`$ go build .`
`go: github.com/pierrec/lz4@v0.0.0-20190907084501-f25943004a39: go.mod has post-v0 module path "github.com/pierrec/lz4/v3" at revision f25943004a39`
`go: error loading module requirements`

Did I miss something or is it not supported yet ?

Regards,

EDIT : I'm using go1.12.9

**Comment by pierrec** [comment]
Hello,

Make sure that you import with the v3 trailing version.
i.e.
```
import "github.com/pierrec/lz4/v3"
```

**Comment by GuillaumeLescure** [comment]
My bad, if I use the import and not directly require it in the module file, it works.
I'm not yet completly familiar with go module system.

Sorry for the inconvenient.

PS : thanks for the great work, I will use it in my projects :wink:
