### ISSUE TITLE
Block compression incompatibility with C/Python library

### ISSUE THREAD

**Issue by tobgu** [pierrec/lz4#58]
Since commit https://github.com/pierrec/lz4/commit/a207029655a0aa70c4cba8263c5aa8d273f9b28c (identified through bisecting) compressing some data causes the Python/C decompressor to fail with error message `_block.LZ4BlockError: Decompression failed: corrupt input or insufficient space in destination buffer. Error code: 179`. 

The problem seems to be that the decompressor cannot fit the decompressed data within the provided buffer size (which is the size of the original data). Or is somehow tricked into thinking it cannot fit the data. Increasing the provided size by one resolves the problem in all cases observed so far.

Below is a Go compressor and Python decompressor pair that demonstrates the problem. The input data provided is the smallest I managed to identify that would reproduce the problem:

```go
package main

import (
	"fmt"
	"github.com/pierrec/lz4"   // v2.3.0
	"os"
)


func check(err error) {
	if err != nil {
		panic(err)
	}
}

func main() {
        // 214 bytes
	originalInput := []byte(`[{"rqgulitaeas_bitmap":0,"mwsswng_afnce":null,"fm_rxposire_op":null,"lnpmct_abs_diff_pct":null,"pqrstuvwyx_pxtch_eating":null,"fm_wxpssxre_rbs_dwxx_pct":null,"ued_date":"2020-09-15","regglttabns_bitmap_op":0,"dfff_`)
	input := originalInput
	var ht [1 << 16]int
	dst := make([]byte, lz4.CompressBlockBound(len(input)))
	fmt.Printf("Dst size: %d, input size: %d, original size: %d\n", len(dst), len(input), len(originalInput))
       
	size, err := lz4.CompressBlock(input, dst, ht[:])
	check(err)

	if size == 0 {
		fmt.Println("Uncompressible!")
		return
	}

        // No problem decompressing using Go lz4 with the exact size of the input
	uncompressedBuf := make([]byte, len(input))
	_, err = lz4.UncompressBlock(dst[:size], uncompressedBuf)
	check(err)

	f, err := os.Create(fmt.Sprintf("test_compressed_%d.lz4", len(input)))
	check(err)
	defer f.Close()

	_, err = f.Write(dst[:size])
	check(err)
}
```

```python
# Python 3.7.4
# LZ4 2.2.1

import lz4.block

size = 214
with open(f'test_compressed_{size}.lz4', mode='rb') as f:
    # This crashes
    lz4.block.decompress(f.read(), uncompressed_size=size)
   
    # This works
    # lz4.block.decompress(f.read(), uncompressed_size=size+1)
```

Is this a bug in github.com/pierrec/lz4, a bug in the C implementation or something I just have to live with and deal with?

**Comment by pierrec** [comment]
This is definitely a bug, thank you for reporting and providing a reproducer.
I will have a look and try to fix it asap, unless you beat me to it ;).

**Comment by pierrec** [comment]
Here are my findings:
- the go package can compress/uncompress your sample string just fine
- same for the C version of lz4 (*** LZ4 command line interface 64-bits r128, by Yann Collet (Apr  3 2018) ***)
- python with module lz4 at 2.2.1 fails with the error message you mention

Maybe worth checking with the maintainer of the python package maybe?

**Comment by tobgu** [comment]
Thanks for investigating this! I've opened a case with the Python lib and we'll see where it goes.

**Comment by klauspost** [comment]
It could be that `mfLimit` should be adjusted.

Does the error still happen if you change [this line](https://github.com/pierrec/lz4/blob/master/lz4.go#L41:2) to `mfLimit = 8 + minMatch + 2`
