### ISSUE TITLE
Incorrect tags on latest versions

### ISSUE THREAD

**Issue by klauspost** [pierrec/lz4#59]
The latest releases have incorrect semantic versioning tags, missing the `v`.

**Comment by pierrec** [comment]
Oups. Sorry about that, will fix ASAP, probably tomorrow.

**Comment by mholt** [comment]
Thanks, will be looking forward to this! :) Have some very confused users right now.

**Comment by pierrec** [comment]
Sorry for the delay. Done.

**Comment by mholt** [comment]
Thank you!!

**Comment by pstibrany** [comment]
I'm confused... what is the latest version to use?

`go get github.com/pierrec/lz4` gives me `v2.4.0+incompatible`, and `go get github.com/pierrec/lz4@v3.2.0` complains about `invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v3`.

**Comment by pstibrany** [comment]
Ah, sorry my bad. It should be `go get github.com/pierrec/lz4/v3`. One day I'll understand all the details of Go module system.
