### ISSUE TITLE
Why it is very slower than snappy ?

### ISSUE THREAD

**Issue by StephaneBunel** [pierrec/lz4#60]
Hi,
My test case is a pure JSON file of 223179 bytes. I use this code:

zbuf := make([]byte, lz4.CompressBlockBound(len(data)))
winSize := 128 * 1024
zsize, err := lz4.CompressBlockHC(data, zbuf, winSize)

LZ4: 5.54 ms
Snappy: 258 µs

Snappy (github.com/golang/snappy) is more than 20X faster !!

According to  benchmark, LZ4 should be faster than Snappy:
https://www.percona.com/blog/2016/04/13/evaluating-database-compression-methods-update/
https://gist.github.com/kevsmith/4217004
https://doordash.engineering/2019/01/02/speeding-up-redis-with-compression/
...

**Comment by pierrec** [comment]
Hello,

lz4.CompressBlockHC is definitely slow.
Try it with lz4.CompressBlock.
LZ4 is definitey competitive with Snappy, even this Go implementation, see #55.

**Comment by StephaneBunel** [comment]
Hello,

Yes, lz4.CompressBlock is definitely faster. A little bit slower than Snappy but with a better compression ratio on my test case. Well done !
Thank you for update.
