### ISSUE TITLE
compress time formate by time.RFC3339 failed, compressed byte slice len is 0

### ISSUE THREAD

**Issue by refine36** [pierrec/lz4#63]
`	data := []byte(`{"CreatedAt":"2019-12-29T20:56:26.535143+08:00"}`)
	buf := make([]byte, len(data))
	ht := make([]int, 64<<10) // buffer for the compression table

	n, err := lz4.CompressBlock(data, buf, ht)
	if err != nil {
		fmt.Println(err)
	}
	if n >= len(data) {
		fmt.Printf("`%s` is not compressible", string(data))
	}
	fmt.Println("compressed len", n)
	buf = buf[:n] // compressed data

	// Allocated a very large buffer for decompression.
	out := make([]byte, 10*len(data))
	n, err = lz4.UncompressBlock(buf, out)
	if err != nil {
		fmt.Println(err)
	}
	out = out[:n] // uncompressed data

	fmt.Println(string(out[:len(data)]))`

output:
compressed len 0

**Comment by pierrec** [comment]
As per the doc, if there is no error and the compressed size is 0, then the data is NOT compressible.
Let me know if the documentation needs refining, thanks.

**Comment by refine36** [comment]
> As per the doc, if there is no error and the compressed size is 0, then the data is NOT compressible.
> Let me know if the documentation needs refining, thanks.

my src []byte is {"CreatedAt":"2019-12-29T20:56:26.535143+08:00"}
so as the doc means，this kind of slice is NOT compressible?
but it is compressible when i use github.com/golang/snappy

**Comment by pierrec** [comment]
Being not compressible here means that the compressed size would be bigger than the input one.

See: https://play.golang.org/p/k8otsp5Zo-i
where the snappy output is bigger.

**Comment by pierrec** [comment]
Does this make sense or do you need more?
