### ISSUE TITLE
Provide block compression functions that are guaranteed to succeed

### ISSUE THREAD

**Issue by slon** [pierrec/lz4#71]
Currenty both `CompressBlock` and `CompressBlockHC` refuse to compress some blocks.

> The size of the compressed data is returned. If it is 0 and no error, then the data is incompressible. 

That causes interoperability problems, when talking to software that uses block format directly.

https://github.com/lz4/lz4/blob/v1.8.3/lib/lz4.h#L129

> Compression is guaranteed to succeed if 'dstCapacity' >= LZ4_compressBound(srcSize).

C implementation guarantees that block would be compressed, provided output buffer is large enough.

**Comment by pierrec** [comment]
That is a good point.
Although the Compress* functions were originally only provided for convenience, it seems that they are actively used as per their C counterpart.
I will look into making the Go versions compatible with C's.
Any suggestion welcome!

**Comment by slon** [comment]
Here are my thoughts. Please correct me if I am wrong.

- Block level functions "refuse" to compress blocks, that would become bigger after compression. That is used in streaming format, where incompressible blocks are transmitted as-is, saving space.
- There is upper bound on block size after compression. n + n/255 + 16, as given by CompressBlockBound function. Most code that uses block compression directly allocates output buffer of this size already.

I think we should provide the same guarantee as a C library:
> Compression is guaranteed to succeed if 'dstCapacity' >= LZ4_compressBound(srcSize).
Update documentation about n = 0 case.
> The size of the compressed data is returned. If it is 0 and no error, then the compressed data is larger than output buffer.
And update stream compression code to pass smaller output buffer size.

That change would fix all user code, that is currently calling Compress* functions without handling n==0 case. I think there is a big share of such code, because I created this issue after encountering this exact problem twice I two completely unrelated systems.
