### ISSUE TITLE
Documentation about version differences.

### ISSUE THREAD

**Issue by cyriltovena** [pierrec/lz4#73]
Hello Pierre !

I've just realized there is v2, v3 and v4. I'm wondering what's the differences between those ? any reasons to use v3 or v4 over v2 ?

Thank you !

**Comment by cyriltovena** [comment]
From my research it seems that v2 and v3 are the same. but v4 looks interesting it seems that it uses more `sync.Pool` ?

**Comment by pierrec** [comment]
Hi Cyril,

v2 is the same as master.
v3 is based on Go modules.
v4 is a complete rewrite of the Reader and Writer to be more Go like. I started learning Go developing this library and have learnt a bit since then!

v4 being worked on, although it is mostly done.
